### ISSUE TITLE
A 20-character anti-spam parameter  what does means

### ISSUE THREAD

**Issue by xkser** [szdc/musically-api#14]
export interface AntiSpamParams {
  /** A 20-character anti-spam parameter */
  as: string;

  /** A 20-character anti-spam parameter */
  cp: string;

  /** An encoded version of the 'as' anti-spam parameter */
  mas: string;
}

how do create as and mas？？？？？

**Comment by szdc** [comment]
You'll need to reverse engineer the app to come up with a solution that you then pass in as the `signURL` option to this library.

I'm closing this as it's related to #9.
